/*  The MIT License

Copyright (c) 2011 TidePowerd Limited (http://www.tidepowerd.com)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

*/

// GPU.NET Example Project : Monte Carlo (C# Excel2007)
// More examples available at http://github.com/tidepowerd

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace TidePowerd.Example.CSharp.Excel2007.MonteCarlo {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(2)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet2 : Microsoft.Office.Tools.Excel.Worksheet {
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_NumberOfTimeSteps;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_NumberOfScenarios;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_Spot;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_Strike;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_RiskFreeRate;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_Volatility;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_Tenor;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Sheet2_OptionType;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet2() : 
                base("Sheet2", "Sheet2") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet2 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.Sheet2_NumberOfTimeSteps.BeginInit();
            this.Sheet2_NumberOfScenarios.BeginInit();
            this.Sheet2_Spot.BeginInit();
            this.Sheet2_Strike.BeginInit();
            this.Sheet2_RiskFreeRate.BeginInit();
            this.Sheet2_Volatility.BeginInit();
            this.Sheet2_Tenor.BeginInit();
            this.Sheet2_OptionType.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.Sheet2_OptionType.EndInit();
            this.Sheet2_Tenor.EndInit();
            this.Sheet2_Volatility.EndInit();
            this.Sheet2_RiskFreeRate.EndInit();
            this.Sheet2_Strike.EndInit();
            this.Sheet2_Spot.EndInit();
            this.Sheet2_NumberOfScenarios.EndInit();
            this.Sheet2_NumberOfTimeSteps.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.Sheet2_NumberOfTimeSteps = new Microsoft.Office.Tools.Excel.NamedRange(this.ItemProvider, this.HostContext, "Sheet2!NumberOfTimeSteps", this, "Sheet2_NumberOfTimeSteps");
            this.Sheet2_NumberOfScenarios = new Microsoft.Office.Tools.Excel.NamedRange(this.ItemProvider, this.HostContext, "Sheet2!NumberOfScenarios", this, "Sheet2_NumberOfScenarios");
            this.Sheet2_Spot = new Microsoft.Office.Tools.Excel.NamedRange(this.ItemProvider, this.HostContext, "Sheet2!Spot", this, "Sheet2_Spot");
            this.Sheet2_Strike = new Microsoft.Office.Tools.Excel.NamedRange(this.ItemProvider, this.HostContext, "Sheet2!Strike", this, "Sheet2_Strike");
            this.Sheet2_RiskFreeRate = new Microsoft.Office.Tools.Excel.NamedRange(this.ItemProvider, this.HostContext, "Sheet2!RiskFreeRate", this, "Sheet2_RiskFreeRate");
            this.Sheet2_Volatility = new Microsoft.Office.Tools.Excel.NamedRange(this.ItemProvider, this.HostContext, "Sheet2!Volatility", this, "Sheet2_Volatility");
            this.Sheet2_Tenor = new Microsoft.Office.Tools.Excel.NamedRange(this.ItemProvider, this.HostContext, "Sheet2!Tenor", this, "Sheet2_Tenor");
            this.Sheet2_OptionType = new Microsoft.Office.Tools.Excel.NamedRange(this.ItemProvider, this.HostContext, "Sheet2!OptionType", this, "Sheet2_OptionType");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_NumberOfTimeSteps)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_NumberOfScenarios)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_Spot)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_Strike)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_RiskFreeRate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_Volatility)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_Tenor)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_OptionType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            // 
            // Sheet2_NumberOfTimeSteps
            // 
            // 
            // Sheet2_NumberOfScenarios
            // 
            // 
            // Sheet2
            // 
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_NumberOfTimeSteps)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_NumberOfScenarios)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_Spot)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_Strike)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_RiskFreeRate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_Volatility)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_Tenor)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Sheet2_OptionType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.Sheet2_OptionType.Dispose();
            this.Sheet2_Tenor.Dispose();
            this.Sheet2_Volatility.Dispose();
            this.Sheet2_RiskFreeRate.Dispose();
            this.Sheet2_Strike.Dispose();
            this.Sheet2_Spot.Dispose();
            this.Sheet2_NumberOfScenarios.Dispose();
            this.Sheet2_NumberOfTimeSteps.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet2 _Sheet2;
        
        internal static Sheet2 Sheet2 {
            get {
                return _Sheet2;
            }
            set {
                if ((_Sheet2 == null)) {
                    _Sheet2 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
